# Custom Language File for Launcher Customizer

[ejs.app]
title = "모리 서버 런처"

[ejs.landing]
mediaGitHubURL = "https://cafe.naver.com/goldmori"
mediaYouTubeURL = "https://www.youtube.com/@goldmori_games"
mediaDiscordURL = "https://cafe.naver.com/goldmori"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "모리 서버에 오신 것을 환영합니다"
welcomeDescription = ""
welcomeDescCTA = ""
