# Custom Language File for Launcher Customizer

[ejs.app]
title = "FlowVillage Launcher"

[ejs.landing]
mediaGitHubURL = "https://flowonline.notion.site/37a6ff70a1c54c67950005b13fa01a00"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.com/invite/HTqj3Nnx8p"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "환영합니다."
welcomeDescription = "플로우 빌리지의 전용 런처 입니다. <진행> 버튼을 눌러주세요!"
welcomeDescCTA = ""
